apiVersion: v1
kind: Service
metadata:
  name: network-security-service
spec:
  selector:
    app: network-security-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080